@HostAddress = https://localhost:5001/accg
@timeout = 600000

### Script
GET {{HostAddress}}/home
Accept: application/json

### Create Chart of Account
POST {{HostAddress}}/chartofaccount
Content-Type: application/json
Accept: application/json

{
  "Code": "personal",
  "Name": "Kyle COA",
  "IsActive" : true,
  "DisplayOrder": 2
}

### Update Chart of Account
PUT {{HostAddress}}/chartofaccount/1dd4e245-8ffd-45d3-826c-a89e869c791e
Content-Type: application/json
Accept: application/json

{
  "Id": "1dd4e245-8ffd-45d3-826c-a89e869c791e",
  "Code": "personal",   
  "Name": "Kyle COA Updated",
  "IsActive": true,
  "DisplayOrder": 3
}

### Search active Chart of Accounts
GET {{HostAddress}}/chartofaccount/search?searchTerm=COA&showHidden=true
Accept: application/json

### Create Account
POST {{HostAddress}}/account
Content-Type: application/json
Accept: application/json

{
  "ChartOfAccountId": "ab4a3724-8b1c-4fa9-ada0-462c7c132cbf",
  "Code": "111",
  "Name": "Cash",
  "AccountType": "cash",
  "IsActive" : true
}

### Get all active Accounts by Chart of Account Id
GET {{HostAddress}}/account/GetAll?ChartOfAccountId=ab4a3724-8b1c-4fa9-ada0-462c7c132cbf
Accept: application/json

### Get all Accounts by Chart of Account Id
GET {{HostAddress}}/account/GetAll?ChartOfAccountId=ab4a3724-8b1c-4fa9-ada0-462c7c132cbf&ShowHidden=true
Accept: application/json
